<a href="https://colab.research.google.com/github/vnzhere/Python-/blob/main/Data_Collection_for_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Collection**



Where to collect data?
/Kaggle
/UCI ml repo
/google dataset search

*  Importance of data in machine learning?
/Dog & cat— ml model—-dog or cat

*   Where to collect data?
1. Kaggle
2. UCI ml repo
3. google dataset search

In [1]:
import pandas as pd

In [2]:
#loading a dataset to pandas dataframe
dataset= pd.read_csv('/content/sample_data/california_housing_train.csv')

In [3]:
dataset.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
#API - Application Programming Interactive

In [4]:
#installing a kaggle library
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.2.25)

Upload your kaggle.json file

In [5]:
#configuring path of kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [6]:
  #Importing earthquake dataset
  # API to fetch dataset from kaggle
!kaggle competitions download -c LANL-Earthquake-Prediction

Downloading LANL-Earthquake-Prediction.zip to /content
100% 2.27G/2.27G [00:30<00:00, 80.3MB/s]

In [8]:
#extracting the compressed dataset
from zipfile import ZipFile
dataset= '/content/LANL-Earthquake-Prediction.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

The dataset is extracted

**Handling Missing Values**


* Imputation
* Dropping

Importing the libraries

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
#loading dataset to a pandas dataaset
dataset = pd.read_csv('/content/iris.csv', encoding='latin1')

In [12]:
!file /content/iris.csv
!head -n 5 /content/iris.csv

/content/iris.csv: Zip archive data, at least v2.0 to extract, compression method=deflate
Yv��~5,�v�xl=���b��{�|������>����wg���+��3d@o��e�;��
Yv\\?��@��F+���T7]l���h{�؇��\{G��4� ���+�2No��e�w0+�f{�s��m�}+��	�V��=��[���[�]	���ۡ��Fϊ��W�j��q���ޓ�OcO8Y�ѹ��}��Sm�?�-v@NU�?l7vD���PK��P6  �  PK   ���V            
   iris.names�V]s�8|��U{+UQ(}��*�o�-��YN��"!	��m������U�æE"9���=�Ҩ%�x��H[����ʠ�_�\�*��*Jh{�K����z��s��uȼ*��N�����,��I2�q��TX&�:�K�^���%=����pP����ҕ�|o���T��҇�4�:����������ۯ�j'�τ�A��{�6�Y�����+sJi��ϓd$�^����WG��YD�T:GGiO�BGe��Ǐ�>+�H�?کg���q�_<UA��ѱ2�.�B
ZZ{= pX�I��'�Od�3у?V�T�N��X3T邤�\l�������~Ԛ���T^e��;�@��,G�΅7X���:ɜ��ky"Ο�x4�G��]��Km9d"���A���i}{I��eJ�pꛌ{STK���Ē*�s����/����Mל�9�R�ܚ���$ϖ�S��64�YTu��/I)�g<(��0D߲P��x��P� �C���w�m��c��y˾d�7'��Z����;�-�����
�S��Fr�&�N+�:zy�ø���Ϋ�T0���dȹ<!u�i�ю

In [13]:
dataset.head()

,PK,Ê,æâ20RpIMV0´´4S,|ðç: CJÃÒx×{{^{;xMkûãYf?zª)í6\t` óåQ³kwwÇÇÛDÏ ÏÈ,9¡sË+¶# \óïûí~}ûüõy{Éö~6®¸îÇí¯¸¶l;[ù ï¿.Oãm:^ð>Wo qó+?\ÖþäôO
0,/mìà¡áÓÁÁõÛ¥÷ãé×ùÉôñæ6_ýu~óç1{´Üöù:,íÍ^o Mj.þ»õç¼Ê<8,NaN,NaN,NaN
1,Yv¿¸~ 5,Õv­xl=¥ºébß{|¯û¸ûî>×ÞÑßwgà²Óá+áÀ3d@o¶...,NaN,NaN,NaN
2,³½ànclÅÙ;ùªU»oñ Ö÷-ßÒóÉ-Á®¼âýÛ¡½S#²b¶ÿAÍ...,5,~uã% KÙøó}ìhF,NaN,NaN
3,"KÿáÝ`s""/½þ©&7ÈÓýñÉ½Ï~ôTSÚm±/]ëìxw <Þ...",±´7£Þ: «¹àwëÏy'!8,NaN,NaN,NaN
4,Yv\\?@µÝF+­§T7]lÀ½çh{­Øî»û\{G¼ï4Î,NaN,NaN,NaN,NaN